import type { FalseFriend } from "./types";

// Falsos amigos: el error que más delata a un hispanohablante, porque no suena
// a error. La tabla da las cuatro cosas que hacen falta: qué parece, qué
// significa de verdad, cómo se dice lo que uno quería decir y un ejemplo.
export const FALSE_FRIENDS: FalseFriend[] = [
  { en: "actually", looksLike: "actualmente", means: "en realidad, de hecho", sayInstead: "currently", example: "Actually, I never said that." },
  { en: "eventually", looksLike: "eventualmente", means: "al final, con el tiempo", sayInstead: "occasionally", example: "Eventually they agreed to pay." },
  { en: "embarrassed", looksLike: "embarazada", means: "avergonzado", sayInstead: "pregnant", example: "I was embarrassed to ask again." },
  { en: "sensible", looksLike: "sensible", means: "sensato", sayInstead: "sensitive", example: "Wearing a helmet is the sensible thing to do." },
  { en: "sympathetic", looksLike: "simpático", means: "comprensivo", sayInstead: "nice, friendly", example: "My boss was sympathetic about the delay." },
  { en: "library", looksLike: "librería", means: "biblioteca", sayInstead: "bookshop, bookstore", example: "I study at the library on Sundays." },
  { en: "carpet", looksLike: "carpeta", means: "alfombra", sayInstead: "folder", example: "There's a red carpet in the hall." },
  { en: "constipated", looksLike: "constipado", means: "estreñido", sayInstead: "to have a cold", example: "He said he was constipated, not that he had a cold." },
  { en: "exit", looksLike: "éxito", means: "salida", sayInstead: "success", example: "The exit is on your left." },
  { en: "fabric", looksLike: "fábrica", means: "tela", sayInstead: "factory", example: "This fabric is very soft." },
  { en: "assist", looksLike: "asistir (a un sitio)", means: "ayudar", sayInstead: "attend", example: "A nurse will assist the doctor." },
  { en: "attend", looksLike: "atender", means: "asistir a", sayInstead: "to serve, to help", example: "Two hundred people attend the conference every year." },
  { en: "realize", looksLike: "realizar", means: "darse cuenta", sayInstead: "to carry out", example: "I didn't realize the shop was closed." },
  { en: "support", looksLike: "soportar (aguantar)", means: "apoyar", sayInstead: "to put up with", example: "Thanks for the support during the move." },
  { en: "molest", looksLike: "molestar", means: "acosar sexualmente", sayInstead: "to bother, to annoy", example: "Nobody should molest anyone; use «bother» for annoying." },
  { en: "introduce", looksLike: "introducir (meter)", means: "presentar (a alguien)", sayInstead: "to insert", example: "Let me introduce my colleague." },
  { en: "argument", looksLike: "argumento (de una película)", means: "discusión", sayInstead: "plot", example: "They had an argument about money." },
  { en: "discussion", looksLike: "discusión (pelea)", means: "debate tranquilo", sayInstead: "argument, row", example: "We had a long discussion about the budget." },
  { en: "advertisement", looksLike: "advertencia", means: "anuncio publicitario", sayInstead: "warning", example: "I saw the advertisement on the bus." },
  { en: "notice", looksLike: "noticia", means: "aviso / darse cuenta", sayInstead: "news", example: "Did you notice the sign on the door?" },
  { en: "compromise", looksLike: "compromiso (cita)", means: "acuerdo con concesiones", sayInstead: "commitment, appointment", example: "We reached a compromise on the price." },
  { en: "resume", looksLike: "resumir", means: "reanudar", sayInstead: "to summarize", example: "Talks will resume on Monday." },
  { en: "record", looksLike: "recordar", means: "grabar / registro", sayInstead: "to remember", example: "Please record the meeting." },
  { en: "large", looksLike: "largo", means: "grande", sayInstead: "long", example: "We need a large table for eight." },
  { en: "actual", looksLike: "actual", means: "real, verdadero", sayInstead: "current, present", example: "The actual cost was much higher." },
  { en: "casualty", looksLike: "casualidad", means: "víctima", sayInstead: "coincidence", example: "There was one casualty in the accident." },
  { en: "college", looksLike: "colegio", means: "universidad / instituto superior", sayInstead: "school", example: "She's in her first year of college." },
  { en: "conductor", looksLike: "conductor (de coche)", means: "director de orquesta / revisor", sayInstead: "driver", example: "The conductor raised his baton." },
  { en: "deception", looksLike: "decepción", means: "engaño", sayInstead: "disappointment", example: "The whole scheme was based on deception." },
  { en: "disgust", looksLike: "disgusto", means: "asco", sayInstead: "upset, annoyance", example: "She looked at the plate with disgust." },
  { en: "estate", looksLike: "estado", means: "finca / patrimonio", sayInstead: "state", example: "They sold the family estate." },
  { en: "grocery", looksLike: "grosería", means: "tienda de comestibles", sayInstead: "rude remark", example: "I need to do the grocery shopping." },
  { en: "idiom", looksLike: "idioma", means: "modismo", sayInstead: "language", example: "«Bite the bullet» is a common idiom." },
  { en: "lecture", looksLike: "lectura", means: "clase magistral", sayInstead: "reading", example: "The lecture starts at nine." },
  { en: "parents", looksLike: "parientes", means: "padres", sayInstead: "relatives", example: "My parents live in Seville." },
  { en: "pretend", looksLike: "pretender", means: "fingir", sayInstead: "to intend, to aim to", example: "Don't pretend you didn't know." },
  { en: "quiet", looksLike: "quieto", means: "silencioso", sayInstead: "still", example: "The office is very quiet today." },
  { en: "rope", looksLike: "ropa", means: "cuerda", sayInstead: "clothes", example: "Tie the rope to the post." },
  { en: "sane", looksLike: "sano", means: "cuerdo", sayInstead: "healthy", example: "Nobody sane would agree to that." },
  { en: "soap", looksLike: "sopa", means: "jabón", sayInstead: "soup", example: "There's no soap in the bathroom." },
  { en: "terrific", looksLike: "terrorífico", means: "estupendo", sayInstead: "terrifying", example: "You did a terrific job." },
  { en: "topic", looksLike: "tópico (cliché)", means: "tema", sayInstead: "cliché", example: "Let's move on to the next topic." },
  { en: "ultimately", looksLike: "últimamente", means: "en última instancia", sayInstead: "lately, recently", example: "Ultimately, it's your decision." },
  { en: "vase", looksLike: "vaso", means: "jarrón", sayInstead: "glass", example: "She put the flowers in a vase." },
  { en: "billion", looksLike: "billón", means: "mil millones", sayInstead: "trillion", example: "The company is worth a billion dollars." },
  { en: "career", looksLike: "carrera (estudios)", means: "trayectoria profesional", sayInstead: "degree", example: "He changed career at forty." },
  { en: "diversion", looksLike: "diversión", means: "desvío", sayInstead: "fun", example: "There's a diversion on the main road." },
  { en: "familiar", looksLike: "familiar (pariente)", means: "conocido, que suena", sayInstead: "relative", example: "Your face looks familiar." },
  { en: "involve", looksLike: "envolver", means: "implicar", sayInstead: "to wrap", example: "The job involves a lot of travelling." },
  { en: "policy", looksLike: "policía", means: "política (norma)", sayInstead: "police", example: "The company policy is clear about this." },
];
